sonar.projectKey=mitchins_clipdisk
sonar.organization=mitchins
sonar.projectName=clipdisk

sonar.sources=Sources
sonar.tests=Tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=Sources/**/*.xcassets/**,Sources/**/*.png,Sources/**/*.icns
sonar.coverageReportPaths=coverage.xml
